config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    # root :to => "devise/sessions#new"
    # get "sign_in", :to => "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
    # get "sign_up", :to => "devise/registrations#new"
  end

  resources :users, only: [:show]

  namespace :admin do
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end

  resources :payment_intents, only: [:create]
  resources :wished_products, only: [:create, :destroy, :index]
  resources :webhooks, only: [:create]

  root 'pages#home'

  get 'pages/product_detail' => 'pages#product_detail'

  get 'pages/laptop' => 'pages#laptop'

  get 'pages/profile' => 'pages#profile'

  get 'pages/product_category' => 'pages#product_category'

  get 'pages/cart' => 'pages#cart'

  get 'cart/show' => 'cart#show'

  post 'cart/add_product' => 'cart#add_product'

  post 'cart/remove_product' => 'cart#remove_product'

  post 'cart/delete_product' => 'cart#delete_product'

  post 'checkouts/check' => 'checkouts#check'

  post 'payments' => 'payments#create'

  get 'payments/:payment_id/order_details' => 'payments#order_details', as: :payment_order_details

  get 'payments/my_orders' => 'payments#my_orders', as: :my_orders

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/cart_controller.rb
# rubocop:disable Metrics/ClassLength
class CartController < ApplicationController
  include Cart

  def show
    @cart_products = nil
    @cart_data = cart
    if @cart_data.present?
      @cart_products = cart_products(@cart_data)
    else
      redirect_to root_path, notice: 'Cart is empty, please add some products!'
    end
  end

  # rubocop:disable Metrics/PerceivedComplexity
  def add_product
    out_of_stock = false
    product_id = params[:product_id].to_s
    cart_data = cart
    cart_page = params[:cart_page]

    if cart_data[product_id]
      if product_available?(product_id, cart_data[product_id] + 1)
        cart_data[product_id] += 1
      else
        out_of_stock = true
      end
    elsif product_available?(product_id, 1)
      cart_data[product_id] = 1
    else
      out_of_stock = true
    end

    @total_cart_items = cart_data.values.sum

    if out_of_stock
      flash.now[:error] = "This product is out of stock, please choose another product"
    else
      update_cart(cart_data)
      flash.now[:notice] = "Product added to cart successfully" unless cart_page
    end

    turbo_streams = [
      turbo_stream.replace("my_cart", partial: "cart/cart_btn", locals: { pages: @total_cart_items }),
      turbo_stream.replace("flash", partial: "shared/flash")
    ]

    if cart_page
      turbo_streams << turbo_stream.replace(
        "cart_item_quantity_#{product_id}",
        partial: "cart/cart_item_quantity",
        locals: { product: Product.find_by(id: product_id.to_i), cart_data: }
      )

      turbo_streams << turbo_stream.replace(
        "cart_summary",
        partial: "cart/cart_summary",
        locals: { cart_products: cart_products(cart_data), cart_data: }
      )
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_streams
      end
    end
  end
  # rubocop:enable Metrics/PerceivedComplexity

  def remove_product
    product_id = params[:product_id].to_s
    cart_data = cart
    item_deleted = false

    if cart_data[product_id]
      if cart_data[product_id] > 1
        cart_data[product_id] -= 1
      else
        item_deleted = true
        cart_data.delete(product_id)
      end
    end
    @total_cart_items = cart_data.values.sum
    update_cart(cart_data)

    turbo_streams = [
      turbo_stream.replace("my_cart", partial: "cart/cart_btn", locals: { pages: @total_cart_items }),
      turbo_stream.replace("cart_summary", partial: "cart/cart_summary", locals: { cart_products: cart_products(cart_data), cart_data: })
    ]

    turbo_streams << if item_deleted
                       turbo_stream.replace("cart_items", partial: "cart/cart_items", locals: { cart_products: cart_products(cart_data), cart_data: })
                     else
                       turbo_stream.replace("cart_item_quantity_#{product_id}", partial: "cart/cart_item_quantity", locals: { product: Product.find_by(id: product_id.to_i), cart_data: })
                     end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_streams
      end
    end
  end

  def delete_product
    product_id = params[:product_id].to_s
    cart_data = cart
    cart_data.delete(product_id)
    update_cart(cart_data)
    @total_cart_items = cart_data.values.sum
    turbo_streams = [
      turbo_stream.replace("my_cart", partial: "cart/cart_btn", locals: { pages: @total_cart_items }),
      turbo_stream.replace("cart_summary", partial: "cart/cart_summary", locals: { cart_products: cart_products(cart_data), cart_data: })
    ]
    turbo_streams << turbo_stream.replace("cart_items", partial: "cart/cart_items", locals: { cart_products: cart_products(cart_data), cart_data: })
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_streams
      end
    end
  end

  private

  def product_available?(product_id, quantity)
    Product.stock_available?(product_id, quantity)
  end
end
# rubocop:enable Metrics/ClassLength

app/controllers/concerns/cart.rb
module Cart
  extend ActiveSupport::Concern

  def cart
    if cookies[:nexar_cart].present?
      JSON.parse(cookies[:nexar_cart])
    else
      {}
    end
  end

  def update_cart(cart)
    cookies[:nexar_cart] = { value: cart.to_json, expires: 1.week.from_now }
  end

  def delete_cart
    cookies[:nexar_cart] = nil
  end

  def cart_products(cart_data)
    Product.where(id: cart_data.keys).order(id: :asc)
  end

  def order_detail(payment)
    cart_data = payment.order_details
    products = cart_products(cart_data)
    products_array = []
    products.each do |product|
      products_hash = {
        product:,
        quantity: cart_data[product.id.to_s].to_i
      }
      products_array << products_hash
    end

    {
      invoice_date: payment.created_at.to_date,
      amount: payment.price.to_f,
      products_data: products_array,
      invoice_id: payment.id,
      user_first_name: payment.user.first_name,
      shipping_address: payment.shipping_address
    }
  end
end

app/views/cart/_cart_btn.html.erb
<turbo-frame id="my_cart">
  <a href=<%= cart_show_path %> class="border rounded py-1 px-3 nav-link d-flex align-items-center" target="_self"> <i class="fa fa-2x fa-shopping-cart my-cart m-1 me-md-2" value=<%= total_cart_items %>></i></a>
</turbo-frame>

app/views/cart/_cart_item_quantity.html.erb
<turbo-frame id="cart_item_quantity_<%= product.id %>">
  <div class="d-flex mb-4" style="max-width: 300px">
    <%= button_to cart_remove_product_path(product_id: product.id, cart_page: true), method: :post, class: "btn btn-primary px-3 ms-2", data: { mdb_button_init: true, mdb_ripple_init: true }, form: { style: "display: inline;" } do %>
        <i class="fas fa-minus"></i>
    <% end %>
     &nbsp;&nbsp;
    <div  class="form-outline">
      <input id="form1" min="0" readonly name="quantity" value=<%= cart_data[product.id.to_s] %> type="number" class="form-control" />
      <label class="form-label" for="form1">Quantity</label>
    </div>

    <%= button_to cart_add_product_path(product_id: product.id, cart_page: true), method: :post, class: "btn btn-primary px-3 ms-2", data: { mdb_button_init: true, mdb_ripple_init: true }, form: { style: "display: inline;" } do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
</turbo-frame>

<!-- to make the floating label to go back to its default position -->
<script type="text/javascript" charset="utf-8">
  document.querySelectorAll('.form-outline').forEach((formOutline) => {
    // initialize form inputs for mdb
    new mdb.Input(formOutline).init();
  });
</script>

app/views/cart/_cart_items.html.erb
<%= turbo_frame_tag "cart_items" do %>
  <div class="card mb-4">
    <div class="card-header py-3">
      <h5 class="mb-0">My Cart</h5>
    </div>
    <div class="card-body">
      <!-- Single item -->
      <% cart_product_lenght = cart_products.count %>
      <% cart_products.each_with_index do |product, index| %>
        <div class="row">
          <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
            <!-- Image -->
            <div class="bg-image hover-overlay hover-zoom ripple rounded" data-mdb-ripple-color="light">
              <%= image_tag(primary_image_url(product), class: "img-thumbnail", height: "300", width: "300") %>
              <a href="#!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
              </a>
            </div>
            <!-- Image -->
          </div>

          <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
            <!-- Data -->
            <p><strong><%= product.name %></strong></p>
                              <p>Category: <%= product.category.name %></p>
            <!--                  <p>Size: M</p>-->
            <%= button_to cart_delete_product_path(product_id: product.id), method: :post, class: 'btn btn-danger btn-sm me-1 mb-2', data: { mdb_button_init: true, mdb_ripple_init: true, mdb_tooltip_init: true, toggle: 'tooltip' }, title: 'Remove item' do %>
              <i class="fas fa-trash"></i>
            <% end %>
            <!-- Data -->
          </div>

          <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
            <!-- Quantity -->
            <%= render partial: 'cart_item_quantity', locals: { product: product, cart_data: cart_data } %>
            <!-- Quantity -->

            <!-- Price -->
            <p class="text-start text-md-center">
              <strong><%= "$#{product.price}" %></strong>
            </p>
            <!-- Price -->
          </div>
        </div>
        <% if  index < cart_product_lenght - 1 %>
          <hr class="my-4" />
        <% end %>
      <% end %>
      <!-- Single item -->

    </div>
  </div>
<% end %>

app/views/cart/_cart_summary.html.erb
<%= turbo_frame_tag "cart_summary" do %>
  <ul class="list-group list-group-flush">
    <li
      class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
      Total Items
      <span><%= total_items(cart_data) %></span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-center px-0">
      Shipping
      <span>Standard-Delivery-$5.00</span>
    </li>
    <li
      class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
      <div>
        <strong>Total amount</strong>
        <strong>
          <p class="mb-0">(including VAT)</p>
        </strong>
      </div>
      <strong><span id="amount"><%= "$#{total_cart_amount(cart_data, cart_products)}" %><span></strong>
    </li>
  </ul>
<% end %>

app/views/cart/show.html.erb
<!--@cart_products = nil-->
<!--@cart_data = cart-->

<section class="h-100 gradient-custom">
  <div class="container py-2">
    <div class="row d-flex justify-content-center my-4">
      <div class="col-md-8">
        <%= render partial: 'cart_items', locals: { cart_products: @cart_products, cart_data: @cart_data } %>
        <div class="card mb-4">
          <div class="card-body">
            <p><strong>Expected shipping delivery</strong></p>
            <p class="mb-0">12.10.2020 - 14.10.2020</p>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body">
            <p><strong>We accept</strong></p>
            <img class="me-2" width="45px"
                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                 alt="Visa" />
            <img class="me-2" width="45px"
                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                 alt="American Express" />
            <img class="me-2" width="45px"
                 src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                 alt="Mastercard" />

          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="card mb-4">
          <div class="card-header py-3">
            <h5 class="mb-0">Summary</h5>
          </div>
          <div class="card-body">
            <%= render partial: 'cart_summary', locals: { cart_products: @cart_products, cart_data: @cart_data } %>
            <%#= button_to payments_checkout_path, method: :post, form: { id: "checkout-form", data: { turbo: false } },  class: "btn btn-primary btn-lg btn-block" do %>
<!-- Checkout -->
            <%# end %>

            <button class="btn btn-primary btn-lg btn-block" id="checkout-form" data-turbo=false type="submit">
              Checkout
            </button>
          </div>
        </div>
      </div>
      <section class=>
        <div class="container my-5">
          <!-- Modal -->
          <div class="modal fade" id="paymentModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Payment</h5>
                  <button type="button" class="btn-close" data-mdb-ripple-init data-mdb-dismiss="modal"
                          aria-label="Close"></button>
                </div>
                <form action="/payments" method="post" id="new_payment">
                  <div class="modal-body">
                      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                      <input type="hidden" name="payments[stripe_payment_id]" id="payment_id">
                      <input type="hidden" name="payments[price]" id="price">

                      <div class="field">
                        <div id="card"></div>
                      </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-mdb-ripple-init
                            data-mdb-dismiss="modal">Close</button>
  <!--                  <button type="button" class="btn btn-primary" data-mdb-ripple-init>Save changes</button>-->
                    <input type="submit" id="pay_btn" class="btn btn-primary" data-mdb-ripple-init value="">
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>

      <%= content_for :custom_script_after do %>
        <script type=text/javascript >

          var amount = 0;

          // initialize modal
          var myModal = new mdb.Modal(document.getElementById('paymentModal'));

          const csrfToken = document.querySelector('[name="csrf-token"]').getAttribute('content');

          $(document).ready(function() {
            $("body").on('click', '#checkout-form', function(event) {
              event.preventDefault();

              $.ajax({
                url: "<%= checkouts_check_path %>",
                type: 'POST',
                dataType: 'json',
                headers: {
                  'X-CSRF-Token': csrfToken
                },
                data: {}
              }).done(function(ret) {
                 //myModal.show();
                const message = ret["message"];

                if(message == 'sign_in')
                {
                  alert('Please Sign in First !');
                }else if(message == 'shipping_address')
                {
                  alert('Please add shipping address in your profile first !');
                }
                else
                {
                  amount = document.querySelector('#amount').innerText.substring(1);
                  document.querySelector('#price').value = amount;
                  document.querySelector('#pay_btn').value = 'Pay $'+amount;
                  myModal.show();
                }
                 //console.log('ajax done');
              });
            });
          });
        </script>

        <script charset="utf-8">
          var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');
          // load the fonts in
          var fonts = [{
            cssSrc: "https://fonts.googleapis.com/css?family=Karla",
          }];
          // styles for the stripe inputs
          var styles = {
            base: {
              iconColor: "#cccccc",
              color: "#000000",
              fontFamily: "MonumentGroteskTrial-Regular",
              fontSize: "16px",

              "::placeholder": {
                color: "#ccc"
              },
              ":-webkit-autofill": {
                color: "#ccc"
              }
            },
            invalid: {
              iconColor: "#FFC7EE",
              color: "#A31621"
            }
          }

          var elements = stripe.elements();
          var cardElement = elements.create('card', {style: styles});
          cardElement.mount('#card');

          const form = document.querySelector('#new_payment');
          form.addEventListener('submit', function(e) {
            e.preventDefault();
            // Step 1: POST request to create payment intent
            fetch('/payment_intents', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                authenticity_token: '<%= form_authenticity_token %>',
                amount: amount
              }),
            })
              .then((response) => response.json())
              .then((paymentIntent) => {
                // Step 2: Create payment method and confirm payment intent.
                stripe.confirmCardPayment(
                  paymentIntent.client_secret, {
                    payment_method: {
                      card: cardElement
                    }
                  }
                ).then((resp) => {
                  if(resp.error) {
                    alert(resp.error.message);
                  } else {
                    // Step 3: Embed payment ID in form
                    const paymentIdInput = document.querySelector('#payment_id');
                    paymentIdInput.value = paymentIntent.id;
                    form.submit();
                  }
                })
              })
              .catch((error) => {
                console.error('Error:', error);
              });
          });
        </script>
      <% end %>
    </div>
  </div>
</section>