config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    # root :to => "devise/sessions#new"
    # get "sign_in", :to => "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
    # get "sign_up", :to => "devise/registrations#new"
  end

  resources :users, only: [:show]

  namespace :admin do
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end

  resources :payment_intents, only: [:create]
  resources :wished_products, only: [:create, :destroy, :index]
  resources :webhooks, only: [:create]

  root 'pages#home'

  get 'pages/product_detail' => 'pages#product_detail'

  get 'pages/laptop' => 'pages#laptop'

  get 'pages/profile' => 'pages#profile'

  get 'pages/product_category' => 'pages#product_category'

  get 'pages/cart' => 'pages#cart'

  get 'cart/show' => 'cart#show'

  post 'cart/add_product' => 'cart#add_product'

  post 'cart/remove_product' => 'cart#remove_product'

  post 'cart/delete_product' => 'cart#delete_product'

  post 'checkouts/check' => 'checkouts#check'

  post 'payments' => 'payments#create'

  get 'payments/:payment_id/order_details' => 'payments#order_details', as: :payment_order_details

  get 'payments/my_orders' => 'payments#my_orders', as: :my_orders

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/shared/_products.html.erb
<!-- Products -->
<section>
  <div class="container my-2">
    <div class="row">
      <% products.each do |product| %>
        <div class="col-lg-3 col-md-6 col-sm-6">
          <div class="card my-2 shadow-0">
<!--            <i class="fas fa-heart fa-lg heart" align="right"></i>-->
            <!--          <i class="fas fa-heart heart"></i>-->
            <a href="<%= pages_product_detail_path(id: product.id) %>" class="img-wrap">
              <%= image_tag(primary_image_url(product), class: "card-img-top", style: "aspect-ratio: 1 / 1") %>
            </a>
            <!--          <div class="ratings">-->
            <!--            <i class="fa fa-star rating-color"></i>-->
            <!--            <i class="fa fa-star rating-color"></i>-->
            <!--            <i class="fa fa-star rating-color"></i>-->
            <!--            <i class="fa fa-star rating-color"></i>-->
            <!--            <i class="fa fa-star"></i>-->
            <!--          </div>-->
            <div class="card-body p-0 pt-2 mx-5 my-3">
              <h5 align="center" class="card-title">$ <%= product.price %></h5>
              <a href="<%= pages_product_detail_path(id: product.id) %>"><p class="card-text mb-0" align="center" title="<%= product.name %>"><%= truncate(product.name, length: 24, omission: '...') %></p></a>
            </div>
            <!-- Button to add the product to the cart -->
            <%= button_to cart_add_product_path(product_id: product.id), method: :post, class: "btn btn-primary add-to-cart ms-6 mb-4", data: { turbo_frame: "my_cart" } do %>
              <i class="fa fa-shopping-cart"></i> Add to cart
            <% end %>
            <% if request.original_url.include?('wished_products') %>
              <%= button_to wished_product_path(id: product.id), method: :delete, class: "btn add-to-cart btn-outline-danger ms-6 mb-4", data: { turbo: true } do %>
                <i class="fas fa-minus"></i> Remove from wishlist
              <% end %>
            <% else %>
              <% if user_signed_in? %>
                <%= button_to wished_products_path(product_id: product.id), method: :post, class: "btn add-to-cart btn-outline-primary ms-6 mb-4", data: { turbo: false } do %>
                  <i class="fas fa-plus"></i> Add to wishlist
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>
<!-- Products -->