config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  devise_scope :user do
    # root :to => "devise/sessions#new"
    # get "sign_in", :to => "devise/sessions#new"
    get "sign_out", to: "devise/sessions#destroy"
    # get "sign_up", :to => "devise/registrations#new"
  end

  resources :users, only: [:show]

  namespace :admin do
    resources :categories, except: [:show]
    resources :products, except: [:show]
  end

  resources :payment_intents, only: [:create]
  resources :wished_products, only: [:create, :destroy, :index]
  resources :webhooks, only: [:create]

  root 'pages#home'

  get 'pages/product_detail' => 'pages#product_detail'

  get 'pages/laptop' => 'pages#laptop'

  get 'pages/profile' => 'pages#profile'

  get 'pages/product_category' => 'pages#product_category'

  get 'pages/cart' => 'pages#cart'

  get 'cart/show' => 'cart#show'

  post 'cart/add_product' => 'cart#add_product'

  post 'cart/remove_product' => 'cart#remove_product'

  post 'cart/delete_product' => 'cart#delete_product'

  post 'checkouts/check' => 'checkouts#check'

  post 'payments' => 'payments#create'

  get 'payments/:payment_id/order_details' => 'payments#order_details', as: :payment_order_details

  get 'payments/my_orders' => 'payments#my_orders', as: :my_orders

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <title>Nexar EStore</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= javascript_importmap_tags %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%#= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag 'splide-4.0.1.min.js' %>
  <%= javascript_include_tag 'mdb.min.js' %>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
  <%= favicon_link_tag 'svg-icon.ico' %>
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.2/mdb.umd.min.js"
  ></script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
  <!--Main Navigation-->
  <header>
    <!-- Jumbotron -->
    <div class="p-3 text-center bg-white border-bottom">
      <div class="container">
        <div class="row gy-3">
          <!-- Left elements -->
          <div class="col-lg-2 col-sm-4 col-4">
            <a href="/" target="_self" class="float-start">
              <%= image_tag("icon_small.png") %>
            </a>
          </div>
          <!-- Left elements -->

          <!-- Center elements -->
          <div class="order-lg-last col-lg-10 col-sm-8 col-8">
            <div class="d-flex float-end">
              <% if user_signed_in? %>
                <a href=<%= sign_out_path %> class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_self"> <i class="fas fa-sign-out-alt m-1 me-md-2"></i><p class="d-none d-md-block mb-0">Sign out</p> </a>
              <% else %>
                <a href=<%= new_user_session_url %> class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_self"> <i class="fas fa-sign-in-alt m-1 me-md-2" aria-hidden="true"></i><p class="d-none d-md-block mb-0">Sign in</p> </a>
                <a href=<%= new_user_registration_url %> class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_self"> <i class="fas fa-user-circle m-1 me-md-2"></i><p class="d-none d-md-block mb-0">Sign up</p> </a>
              <% end %>
            <!--  <a href="https://github.com/mdbootstrap/bootstrap-material-design" class="me-1 border rounded py-1 px-3 nav-link d-flex align-items-center" target="_blank"> <i class="fas fa-star m-1 me-md-2"></i><p class="d-none d-md-block mb-0">Wishlist</p> </a>-->
              <%= render partial: 'cart/cart_btn' %>
            </div>
          </div>
          <!-- Center elements -->

          <!-- Right elements -->
<!--          <div class="col-lg-5 col-md-12 col-12">-->
<!--            <div class="input-group float-center">-->
<!--              <div class="form-outline">-->
<!--                <input type="search" id="form1" class="form-control" />-->
<!--                <label class="form-label" for="form1">Search</label>-->
<!--              </div>-->
<!--              <button type="button" class="btn btn-primary shadow-0">-->
<!--                <i class="fas fa-search"></i>-->
<!--              </button>-->
<!--            </div>-->
<!--          </div>-->
          <!-- Right elements -->
        </div>
      </div>
    </div>
    <!-- Jumbotron -->

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <!-- Container wrapper -->
      <div class="container justify-content-center justify-content-md-between">
        <!-- Toggle button -->
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarLeftAlignExample" aria-controls="navbarLeftAlignExample" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarLeftAlignExample">
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <!-- Navbar dropdown -->
            <% if user_signed_in? && current_user.user_role? %>
              <li class="nav-item dropdown" data-turbo="false">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                My Account
              </a>
              <!-- Dropdown menu -->
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li>
                  <a class="dropdown-item" href="#">Dashboard</a>
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="<%= user_path(current_user.id) %>">View Profile</a>
                </li>
                <li>
                  <a class="dropdown-item" href="<%= edit_user_registration_path %>">Edit Profile</a>
                </li>
              </ul>
            </li>
            <% end %>

            <% if user_signed_in? && current_user.admin_role? %>
              <li class="nav-item dropdown" data-turbo="false">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown"  aria-expanded="false">
                  Manage
                </a>
                <!-- Dropdown menu -->
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown" data-turbo="false">
                  <li>
                    <a class="dropdown-item" href="<%= admin_categories_path %>">Categories</a>
                  </li>
                  <li><hr class="dropdown-divider" href="<%= admin_products_path %>"/></li>
                  <li>
                    <a class="dropdown-item" href="<%= admin_products_path %>">Products</a>
                  </li>
                </ul>
              </li>
            <% end %>

            <li class="nav-item dropdown" data-turbo="false">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                Products
              </a>
              <!-- Dropdown menu -->
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
               <% product_categories.each do |category | %>
                  <li>
                    <a class="dropdown-item" href="<%= pages_product_category_path(category_id: category.id) %>"><%= category.name %></a>
                  </li>
                  <li><hr class="dropdown-divider" /></li>
                <% end %>
              </ul>
            </li>

            <% if user_signed_in? && current_user.user_role? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= my_orders_path %>">My Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= wished_products_path %>">My Wishlist</a>
              </li>
            <% end %>
          </ul>
          <!-- Left links -->
        </div>
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
  </header>

  <!-- main-content --->
  <!-- flash notice and alerst -->
  <%= render partial: 'shared/flash'%>
  <%= yield %>
  <!-- main content-->

  <!-- Footer -->
  <footer class="text-center text-lg-start text-muted bg-primary mt-3">
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start pt-4 pb-4">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-12 col-lg-3 col-sm-12 mb-2">
            <!-- Content -->
            <a href="#" target="_blank" class="text-white h2">
              MDB 5
            </a>
            <p class="mt-1 text-white">
              © 2024 Copyright: Material Design for Bootstrap v5
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-6 col-sm-4 col-lg-2">
            <!-- Links -->
            <h6 class="text-uppercase text-white fw-bold mb-2">
              Store
            </h6>
            <ul class="list-unstyled mb-4">
              <li><a class="text-white-50" href="#">About us</a></li>
              <li><a class="text-white-50" href="#">Find store</a></li>
              <li><a class="text-white-50" href="#">Categories</a></li>
              <li><a class="text-white-50" href="#">Blogs</a></li>
            </ul>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-6 col-sm-4 col-lg-2">
            <!-- Links -->
            <h6 class="text-uppercase text-white fw-bold mb-2">
              Information
            </h6>
            <ul class="list-unstyled mb-4">
              <li><a class="text-white-50" href="#">Help center</a></li>
              <li><a class="text-white-50" href="#">Money refund</a></li>
              <li><a class="text-white-50" href="#">Shipping info</a></li>
              <li><a class="text-white-50" href="#">Refunds</a></li>
            </ul>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-6 col-sm-4 col-lg-2">
            <!-- Links -->
            <h6 class="text-uppercase text-white fw-bold mb-2">
              Support
            </h6>
            <ul class="list-unstyled mb-4">
              <li><a class="text-white-50" href="#">Help center</a></li>
              <li><a class="text-white-50" href="#">Documents</a></li>
              <li><a class="text-white-50" href="#">Account restore</a></li>
              <li><a class="text-white-50" href="#">My orders</a></li>
            </ul>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-12 col-sm-12 col-lg-3">
            <!-- Links -->
            <h6 class="text-uppercase text-white fw-bold mb-2">Newsletter</h6>
            <p class="text-white">Stay in touch with latest updates about our products and offers</p>
            <div class="input-group mb-3">
              <input type="email" class="form-control border" placeholder="Email" aria-label="Email" aria-describedby="button-addon2" />
              <button class="btn btn-light border shadow-0" type="button" id="button-addon2" data-mdb-ripple-color="dark">
                Join
              </button>
            </div>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <div class="">
      <div class="container">
        <div class="d-flex justify-content-between py-4 border-top">
          <!--- payment --->
          <div>
            <i class="fab fa-lg fa-cc-visa text-white"></i>
            <i class="fab fa-lg fa-cc-amex text-white"></i>
            <i class="fab fa-lg fa-cc-mastercard text-white"></i>
            <i class="fab fa-lg fa-cc-paypal text-white"></i>
          </div>
          <!--- payment --->

          <!--- language selector --->
          <div class="dropdown dropup">
            <a class="dropdown-toggle text-white" href="#" id="Dropdown"  role="button" data-mdb-toggle="dropdown" aria-expanded="false"> <i class="flag-united-kingdom flag m-0 me-1"></i>English </a>

            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="Dropdown">
              <li>
                <a class="dropdown-item" href="#"><i class="flag-united-kingdom flag"></i>English <i class="fa fa-check text-success ms-2"></i></a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
              </li>
              <li>
                <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
              </li>
            </ul>
          </div>
          <!--- language selector --->
        </div>
      </div>
    </div>
  </footer>
  <!-- Footer -->

  <%= yield :custom_script_before %>

  <script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function() {
          // Global Initialization (initialize all components)
          // M.AutoInit();
      });
  </script>
  <%= yield :custom_script_after %>
</body>
</html>